svg_icons:
  default: 'highlighter'
  type: 'list'
  list_type: 'compact'
highlighter_background:
  type: string
  default: "#ff8"
  description: 
    en: "Highlighter color in hexadecimal, css color name or Discourse color variable. Leave blank to use current default."
